### ISSUE TITLE
PHP Fatal error (Nextcloud 18.04, linuxserver/nextcloud:18.0.4-ls79)

### ISSUE THREAD

**Issue by itsthejb** [newroco/emlviewer#15]
Hi there,

I had to disable this plugin due to getting the following errors:

```
CRITICAL -
PHP Fatal error:  Declaration of Symfony\Component\Console\Input\ArrayInput::hasParameterOption($values, bool $onlyParams = false) must be compatible with Symfony\Component\Console\Input\InputInterface::hasParameterOption($values, $onlyParams = false) in /config/www/nextcloud/apps/emlviewer/vendor/symfony/console/Input/ArrayInput.php on line 0
CRITICAL - ['php', '/occ', 'files_external:export', '--all'] returned non-zero exit status 255
```

Seems to have started since the next linux-server image version (current one?). So perhaps this is an issue for them?

In any case, hope that info is useful

Thanks

**Comment by putt1ck** [comment]
Do you know what version of the EML viewer you have deployed?

**Comment by itsthejb** [comment]
Hi. It's version 0.0.12, that's what comes from the app store

**Comment by lucianpricop** [comment]
Closing because we can no longer support NC18
