### ISSUE TITLE
Preview on share link page

### ISSUE THREAD

**Issue by gasparakos** [newroco/emlviewer#20]
Hello,

emlviewer is a great idea!
It would be great if you could see the preview on the share link page.

Thanks

**Comment by lucianpricop** [comment]
Hi. Do you mean like a new tab next to activity, comments, sharing, etc? That sounds good, but might be difficult to fit everything in there.

**Comment by gasparakos** [comment]
Hi, not exactly. When you send somebody the share with link URL and it is opened. That landing page could be a preview. Now only download is available. 
It could be an option (maybe Show preview) among others like 'Allow editing', 'Hide download' etc., as in the attached screenshot.
![Képernyőkép_2020-07-16_14-35-54](https://user-images.githubusercontent.com/10700464/87672608-85e89480-c773-11ea-98b8-e69d7b2336db.png)

**Comment by lucianpricop** [comment]
Hi. I just added this functionality. It's a bit simpler than described. The visitor with the share link will see the eml right away, they can close the emlviewer pane if they wish. There is the download button at the top at all times.
