### ISSUE TITLE
Error trying to obtain eml data

### ISSUE THREAD

**Issue by Michael2222** [newroco/emlviewer#23]
Hello,
if I want to open an email this error occured:
`Error trying to obtain eml data: Could not find file: /Beruflich/FC/Prod DL/PjM/DL/2020/2020-10-08 (D) ZertVB (FH)/Übungen/pma Level-D Zertifizierungsvorbereitung.eml`

If I transfer this mail to the root folder I can open it.
Is there a maximum charachter boder for the path and filename?
Thank you!
  Michael

nc 19.0.3
e mail viewer 0.0.17

**Comment by lucianpricop** [comment]
Sorry, but I can't replicate. I create same folder depth but longer names. E.g /2020-10-08%20(D)%20ZertVB%20(FH)/Beruflich%20FC%20Prod%20DL%20PjM%20DL%202020%202020-10-08%20Übungen/FC/DL/2020/2020%2002%20202/2020-10-08%20(D)%20ZertVB%20(FH)/FC/Übungen and it works well.

Are you sure the path shown in the error is the correct path? Maybe some decoding issues. Can you move the file up the path and let me know at which point it starts to fail?

Thank you for your help!

**Comment by Michael2222** [comment]
Hello,

if I want to open the file in the path "/Beruflich/FC" I can open it.
If I want to open the file in the path "/Beruflich/FC/Prod + DL" the error occured

Now if I change the folder name from "Prod + DL" to "ProdDL" the eml file is displaying.

So perhaps the eml Viewer have trouble with "+" in the path name?
Regards!

**Comment by Michael2222** [comment]
Hello,

now I have try an additional test:
I have create a folder "/Test/X+Y" and store an eml file in it an this error occured:

`Error trying to obtain eml data: Could not find file: /Test/X Y/pma Level-D Zertifizierungsvorbereitung.eml`

You can see in the path from the error message there is no "+" character between X and Y! So the Plugin can't read the eml file.
Regards
  Michael

**Comment by lucianpricop** [comment]
Okay, just as I suspected, + is urlencoding for space, so when decoding it's lost. Thank you for debugging this. Will work on a fix.

**Comment by Michael2222** [comment]
Hello,
now it works fine!
Thank You!
