### ISSUE TITLE
v0.0.19 not compatible with Nextcloud 19.x

### ISSUE THREAD

**Issue by gasparakos** [newroco/emlviewer#27]
After upgrade from v0.0.18 on Nextcloud 19.0.4 we got the:
`Interface 'OCP\\AppFramework\\Bootstrap\\IBootstrap' not found"`
error message, and site brakes.
I don't know how to make compatible with both version. Documentation just talk about differences: https://docs.nextcloud.com/server/latest/developer_manual/app_development/bootstrap.html
Maybe different releases? The upgrade should be prevented, if possible.

**Comment by lucianpricop** [comment]
Apologies for that, I forgot to change the compatibility settings, fixed too late to have an effect. 
I just created release 0.0.21for NC19 and older
