### ISSUE TITLE
Nextcloud is dead: PHP Fatal error:  Interface 'OCP\AppFramework\Bootstrap\IBootstrap' not found

### ISSUE THREAD

**Issue by Sanookmakmak** [newroco/emlviewer#29]
emlviewer is causing that error - neither Nextcloud nor the OCC are working anymore.

How can i uninstall emlviewer without OCC command?

More info: [https://help.nextcloud.com/t/nextcloud-instance-dead-occ-command-not-working-anymore/98605]( https://help.nextcloud.com/t/nextcloud-instance-dead-occ-command-not-working-anymore/98605)

**Comment by putt1ck** [comment]
What version of emlviewer and what version of Nextcloud?

**Comment by lucianpricop** [comment]
Can you try by deleting the app folder completely? Or take release 0.0.21 and overwrite all files without uninstalling.

**Comment by Sanookmakmak** [comment]
Thank you, after renaming the folder to "emlviewer.bak" the Nextcloud instance was working again and i could load the apps page in the admin section of Nextcloud. After renaming the folder again to "emlviewer" i was able to uninstall the app.
