### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by schniepp** [newroco/emlviewer#3]
When I click an .eml file, it first looks like nothing happens, but after a few seconds about 1/3 of the browser window (left side) is covered with a semi-transparent, white box. Nothing else happens... no easy way go back to the folder view.

**Comment by putt1ck** [comment]
Is there no "close" cross top right of the view?

Chris Puttick
+44 7908 997146
http://twoten.is

**Comment by schniepp** [comment]
No, can't see anything. This is the html element:
`<div class="mail-content" style="display: flex;height: 98%;max-width: 768px;margin-left: auto;margin-right: auto;text-align: left;padding-left: 25px;padding-right: 25px;width: 100%;flex-direction: column;">`

I think it's technically not covering 1/3, but the vertical menu on the left side. But definitely no cross or anything. This is in Chrome.

**Comment by small1** [comment]
This is how it looks like on most of my servers. 

![Screenshot from 2019-12-16 15-04-57](https://user-images.githubusercontent.com/317830/70913294-0bf20080-2016-11ea-81b9-1654dfe439d8.png)

Using Chrome on linux  connecting to  Nextcloud 17.0.1 servers.

**Comment by putt1ck** [comment]
So a quick test on a 17.01 server here gets me the same (an eml file rendered as it would in email client) in Chrome or FF. Similarly in 16.06:
![image](https://user-images.githubusercontent.com/2872580/70914382-c7fbfd00-200f-11ea-92a2-f291dd3acfc3.png)
Maybe suggests the viewer isn't loading for some reason?

**Comment by small1** [comment]
Now i did a test with ALL apps except this one active and i still get an empty result with a broken view. 

Do i have a missing dependency or is it a config issue? I use nginx and from what i can see i get a 302 on the POST to emlparse.php

I dont seem to get anything back from it.

**Comment by small1** [comment]
Ok i renamed emlparse.php and i still get a 302. It does not post anything to the parser in my config.

**Comment by putt1ck** [comment]
nginx may be the factor, as the client who funded the work uses apache the testing/development would have been in that environment.

**Comment by small1** [comment]
So confirmed. The default nginx config does not execute to emlparse.php file it sends a 302 so the email never gets parsed. 

Adding this:

`	location ~ ^/apps/emlviewer/ajax/emlparse.php {
		fastcgi_split_path_info ^(.+\.php)(/.*)$;
		include fastcgi_params;
		include /etc/nginx/conf.d/php_optimization.conf;
		fastcgi_pass php-handler;
		fastcgi_param HTTPS on;
	}
`
In the nginx conf makes a huge difference and everything is showed as it should. 

Perhaps it would be cleaner to use the route.php and have a POST to the page controller would be better. Or?

**Comment by xsus95** [comment]
Same problem for me.

**Comment by incrosnatubogdan** [comment]
@small1 it should be working on nginx now, can you please confirm?

**Comment by small1** [comment]
I'll give it a try tomorrow when I'm in Berlin.

/Johan

**Comment by small1** [comment]
> @small1 it should be working on nginx now, can you please confirm?

I applied the patches and removed my nginx conf fixes and it works as it should.  Good work!

**Comment by xsus95** [comment]
@incrosnatubogdan can you publish to store soon? :3

**Comment by xsus95** [comment]
@incrosnatubogdan why the fixes dont geht releases?
