### ISSUE TITLE
Make eml viewer run on NC21 / NC 22 with PHP8 

### ISSUE THREAD

**Issue by fow0ryl** [newroco/emlviewer#32]
Just changed from PHP 7.4 and NC 20.0.7 to PHP 8 and NC 21.
Did not work anymore :(

**Comment by roadrunnerjb** [comment]
RewindIterator::__construct(): Argument #1 ($iterator) must be of type Iterator, SplFixedArray given","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":159,"Previous":{"Exception":"TypeError","Message":"NoRewindIterator::__construct(): Argument #1 ($iterator) must be of type Iterator, SplFixedArray given","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/Consumer/AbstractConsumer.php","line":126,"function":"__construct","class":"NoRewindIterator","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/Consumer/AbstractConsumer.php","line":76,"function":"parseRawValue","class":"ZBateson\\MailMimeParser\\Header\\Consumer\\AbstractConsumer","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/AbstractHeader.php","line":75,"function":"__invoke","class":"ZBateson\\MailMimeParser\\Header\\Consumer\\AbstractConsumer","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/ParameterHeader.php","line":46,"function":"setParseHeaderValue","class":"ZBateson\\MailMimeParser\\Header\\AbstractHeader","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/AbstractHeader.php","line":55,"function":"setParseHeaderValue","class":"ZBateson\\MailMimeParser\\Header\\ParameterHeader","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/HeaderFactory.php","line":155,"function":"__construct","class":"ZBateson\\MailMimeParser\\Header\\AbstractHeader","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/HeaderContainer.php","line":153,"function":"newInstance","class":"ZBateson\\MailMimeParser\\Header\\HeaderFactory","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/HeaderContainer.php","line":115,"function":"getByIndex","class":"ZBateson\\MailMimeParser\\Header\\HeaderContainer","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message/Part/PartBuilder.php","line":213,"function":"get","class":"ZBateson\\MailMimeParser\\Header\\HeaderContainer","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message/Part/PartBuilder.php","line":226,"function":"getContentType","class":"ZBateson\\MailMimeParser\\Message\\Part\\PartBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message/Part/PartBuilder.php","line":265,"function":"getMimeBoundary","class":"ZBateson\\MailMimeParser\\Message\\Part\\PartBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message/MessageParser.php","line":173,"function":"setEndBoundaryFound","class":"ZBateson\\MailMimeParser\\Message\\Part\\PartBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message/MessageParser.php","line":230,"function":"findContentBoundary","class":"ZBateson\\MailMimeParser\\Message\\MessageParser","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message/MessageParser.php","line":261,"function":"readPartContent","class":"ZBateson\\MailMimeParser\\Message\\MessageParser","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message/MessageParser.php","line":280,"function":"readPart","class":"ZBateson\\MailMimeParser\\Message\\MessageParser","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message/MessageParser.php","line":65,"function":"read","class":"ZBateson\\MailMimeParser\\Message\\MessageParser","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/MailMimeParser.php","line":75,"function":"parse","class":"ZBateson\\MailMimeParser\\Message\\MessageParser","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message.php","line":78,"function":"parse","class":"ZBateson\\MailMimeParser\\MailMimeParser","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/lib/Controller/PageController.php","line":279,"function":"from","class":"ZBateson\\MailMimeParser\\Message","type":"::"},{"file":"/var/www/nextcloud/apps/emlviewer/lib/Controller/PageController.php","line":43,"function":"parseEml","class":"OCA\\EmlViewer\\Controller\\PageController","type":"->"},{"file":"/var/www/nextcloud/apps/emlviewer/lib/Controller/PageController.php","line":85,"function":"getMessage","class":"OCA\\EmlViewer\\Controller\\PageController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"emlPrint","class":"OCA\\EmlViewer\\Controller\\PageController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/Consumer/AbstractConsumer.php"

**Comment by fow0ryl** [comment]
Just upgraded to 0.0.23. But got "internal server error" when trying to open an eml file.
