### ISSUE TITLE
Composer dependencies for php freezes server

### ISSUE THREAD

**Issue by mghajos** [newroco/emlviewer#36]
Hi, installing the app on machine with php < 7.4.0 will instantly freeze server and render it useless as of Composer dependency.
disabling emlviewer fixes freeze instantly

Terminal:
sudo -u www-data php /var/www/nextcloud/occ list
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.31-1~deb10u1.

NextCloudPi 21.0.4
![grafik](https://user-images.githubusercontent.com/48580875/146131689-0c1ac686-db5e-4deb-b353-4aba51dba3f8.png)

aside of this, app is (was) great :-)
thx, Márton

**Comment by putt1ck** [comment]
PHP 7.3 went EOL last week so it's unlikely much if any time would be spent looking for a fix. While there are some LTS distros that will security patch PHP 7.3 for a little while I'm guessing NCP is not one of them. If you don't have the Docker version you can add the "sury" repo and upgrade to 7.4. I found these NCP specific instructions: https://git.mdns.eu/nextcloud/passwords/-/wikis/Administrators/Guides/NextcloudPi/Upgrade-to-PHP-7.4 - if you have Docker version I'd assume there's an upgrade available for that too.

**Comment by mghajos** [comment]
that was my plan. thx

You should update Your requirements though:
"Requirements
This app requires php version greater than 5 and mbstring and tidy extension"

**Comment by putt1ck** [comment]
Readme updated, thanks for the tip.
