### ISSUE TITLE
Compatibility with NC 23

### ISSUE THREAD

**Issue by schniepp** [newroco/emlviewer#37]
Currently, my NC client states that emlviewer is not compatible with NC v23.

**Comment by schniepp** [comment]
I see that this has been flagged as an "enhancement". Why so? This is not asking for new features, only to make it compatible with the currently released NC version. NC has a quite aggressive release schedule, and pretty soon, older versions will no longer be supported.

**Comment by putt1ck** [comment]
23 is not a version we would recommend someone deploy in production.

**Comment by lucianpricop** [comment]
We'll do it the first moment we have. It's a public repo, contributions are welcome and PRs are welcome
