### ISSUE TITLE
emlviewer and mimetypemapping.json

### ISSUE THREAD

**Issue by eboracum** [newroco/emlviewer#46]
We are running a nextcloud instance and used emlviewer without problems. Until I defined eml as message/RFC822 in config/mimetypemapping.json as a custom mimetype to have eml-files handled by a script. This prevented emlviewer from kicking in, instead the file was offered for download. 

Reason for this behaviour is found in script.js, where eml-files are expected to have mime-type application/octet-stream and not message/rfc822. As a workaround, I changed the entry in mimetypemapping.json from "eml": ["message/rfc822"] to "eml": ["application/octet-stream","message/rfc822"], where the entry application/octet-stream has to precede message/rfc822 in the list. Now emlviewer works again as expected. 

It might be worth a consideration to check for application/octet-stream or message/rfc822 mime-type in a future release.

**Comment by rotdrop** [comment]
There would also the possibility to add the rfc822 mime-type in a post-install "repair" step. However, to my knowledge the update of the database etc. has to be done "manually" by running the appropriate occ commands.
