### ISSUE TITLE
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0".

### ISSUE THREAD

**Issue by piiskop** [newroco/emlviewer#53]
i saw that there were update opportunities in the notifications and went there. _EML Viewer_ was first on the list, _Jitsi Integration_ was the second in the list. i clicked _Update all_. _EML Viewer_ was updated and not the other two apps. Instead, i got this error message. Now, Nextcloud is not usable anymore. This instance is used by many people, so it cannot be down for long. How can i get _Nextcloud_ working again?

**Comment by putt1ck** [comment]
You can disable apps via the command line using the occ tool. What version of Nextcloud are you running on what platform?

**Comment by piiskop** [comment]
[Nextcloud Hub 3](https://nextcloud.com/) (25.0.2)

`kalmer@test:/etc/apache2/mods-enabled$ lsb_release -a`

> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.04.5 LTS
> Release:	20.04
> Codename:	focal
>

**Comment by Luticus** [comment]
I got this too. Devs need to be a lot more careful with the dependencies I think. There are several mainstream Linux distros that are used heavily as servers for nextcloud but do NOT currently package php 8.0+ in their stable release repos. On top of this, Nextcloud still supports 7.4 for now. So imagine my surprise when I updated this one app and had it bring my entire Nextcloud instance down unexpectedly. Disabled for now, but sad because I like the app.

**Comment by lucianpricop** [comment]
I'm sorry about this mishap. Unfortunately I included the vendor folder produced on a machine running php8 even though composer does not require php8 for emlviewer. 
I removed the release archive so others can't install 1.0.5 and will prepare a new release ASAP.

**Comment by Luticus** [comment]
No worries, just took me by surprise is all :). I appreciate you fixing it up so quickly. 

Really I think Nextcloud should ultimately have handled this situation better, if possible. I feel like apps shouldn't be able to bring down the instance like that, rather Nextcloud should refuse to load the app and simply continue working. Not sure what kind of engineering it might take to prevent such a thing from happening in the future, but maybe I'll report a bug to NC and see if they can take a look at it.

**Comment by piiskop** [comment]
> No worries, just took me by surprise is all :). I appreciate you fixing it up so quickly.
> 
> Really I think Nextcloud should ultimately have handled this situation better, if possible. I feel like apps shouldn't be able to bring down the instance like that, rather Nextcloud should refuse to load the app and simply continue working. Not sure what kind of engineering it might take to prevent such a thing from happening in the future, but maybe I'll report a bug to NC and see if they can take a look at it.

i reported there as well and got a quick response to report here although the main problem lies with them. they just do not want to be responsible for their own deficit. Another example is transparent icons for applications that they introduced lately without making sure that they would be visible with any background. Suddenly after the update, nobody could navigate as no link was visible. Again, they did not take the responsibility for that by mentioning how should they know what background a particular user has. Then the file app view is still jumping around and even new emails cannot be found in the mail app. i see a long list every time i update Nextcloud and cannot comprehend what all these updates really are for if essential things are still left untouched. Even for a major release.
