### ISSUE TITLE
Preview of .eml throws error

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [newroco/emlviewer#54]
Versioin NC: 25.0.3
Version EML Viewer: 1.0.6
PHP: 8.1
OS: Ubuntu x64 LTS

Private Information is blacked out

Error:

`[index] Fehler: Exception: NoRewindIterator::__construct(): Argument #1 ($iterator) must be of type Iterator, SplFixedArray given in file '/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/Consumer/AbstractConsumer.php' line 126 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
2. /var/www/nextcloud/lib/base.php line 1047
   OC\Route\Router->match()
3. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

GET /nextcloud/index.php/apps/emlviewer/emlparse?eml_file=%2FArchiev%2FMail%2F2022%2FBLACKEDOUT%2FPostausgang%2FMail%2Fori%20BLACKEDOUT%2FBMW%20IX3.eml&share_token=
from BLACKEDOUT by BLACKEDOUT at 2023-01-20T11:01:43+00:00

/var/www/nextcloud/lib/private/AppFramework/App.php - line 172:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/nextcloud/lib/private/Route/Router.php - line 298:

OC\AppFramework\App::main()

/var/www/nextcloud/lib/base.php - line 1047:

OC\Route\Router->match()

/var/www/nextcloud/index.php - line 36:

OC::handleRequest()

Verursacht durch TypeError: NoRewindIterator::__construct(): Argument #1 ($iterator) must be of type Iterator, SplFixedArray given
/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/Consumer/AbstractConsumer.php - line 126:

NoRewindIterator->__construct()

/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/Consumer/AbstractConsumer.php - line 76:

ZBateson\MailMimeParser\Header\Consumer\AbstractConsumer->parseRawValue()

/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/AbstractHeader.php - line 75:

ZBateson\MailMimeParser\Header\Consumer\AbstractConsumer->__invoke()

/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/ParameterHeader.php - line 46:

ZBateson\MailMimeParser\Header\AbstractHeader->setParseHeaderValue()

/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/AbstractHeader.php - line 55:

ZBateson\MailMimeParser\Header\ParameterHeader->setParseHeaderValue()

/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/HeaderFactory.php - line 155:

ZBateson\MailMimeParser\Header\AbstractHeader->__construct()

/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/HeaderContainer.php - line 153:

ZBateson\MailMimeParser\Header\HeaderFactory->newInstance()

/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Header/HeaderContainer.php - line 115:

ZBateson\MailMimeParser\Header\HeaderContainer->getByIndex()

/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message/Part/PartBuilder.php - line 213:

ZBateson\MailMimeParser\Header\HeaderContainer->get()

/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message/Part/PartBuilder.php - line 226:

ZBateson\MailMimeParser\Message\Part\PartBuilder->getContentType()

/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message/Part/PartBuilder.php - line 265:

ZBateson\MailMimeParser\Message\Part\PartBuilder->getMimeBoundary()

/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message/MessageParser.php - line 173:

ZBateson\MailMimeParser\Message\Part\PartBuilder->setEndBoundaryFound()

/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message/MessageParser.php - line 230:

ZBateson\MailMimeParser\Message\MessageParser->findContentBoundary()

/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message/MessageParser.php - line 261:

ZBateson\MailMimeParser\Message\MessageParser->readPartContent()

/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message/MessageParser.php - line 280:

ZBateson\MailMimeParser\Message\MessageParser->readPart()

/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message/MessageParser.php - line 65:

ZBateson\MailMimeParser\Message\MessageParser->read()

/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/MailMimeParser.php - line 75:

ZBateson\MailMimeParser\Message\MessageParser->parse()

/var/www/nextcloud/apps/emlviewer/vendor/zbateson/mail-mime-parser/src/Message.php - line 78:

ZBateson\MailMimeParser\MailMimeParser->parse()

/var/www/nextcloud/apps/emlviewer/lib/Controller/PageController.php - line 174:

ZBateson\MailMimeParser\Message::from()

/var/www/nextcloud/apps/emlviewer/lib/Controller/PageController.php - line 126:

OCA\EmlViewer\Controller\PageController->parseEml()

/var/www/nextcloud/apps/emlviewer/lib/Controller/PageController.php - line 192:

OCA\EmlViewer\Controller\PageController->getMessage()

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 225:

OCA\EmlViewer\Controller\PageController->emlPrint()

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 133:

OC\AppFramework\Http\Dispatcher->executeController()

/var/www/nextcloud/lib/private/AppFramework/App.php - line 172:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/nextcloud/lib/private/Route/Router.php - line 298:

OC\AppFramework\App::main()

/var/www/nextcloud/lib/base.php - line 1047:

OC\Route\Router->match()

/var/www/nextcloud/index.php - line 36:

OC::handleRequest()`

**Comment by lucianpricop** [comment]
Thanks for this report, I need to upgrade a dependency to make this work on php8 as well. Another release in one day...

**Comment by MrLoverLoverMMMM** [comment]
thank you very much :)
