### ISSUE TITLE
NC22-24 latest release 1.0.5 is not available

### ISSUE THREAD

**Issue by klou** [newroco/emlviewer#55]
I see that 1.0.5 is PHP8.0+, but the listed link in the NC App store for 1.0.5 is incorrect.  So, in-app installs/upgrades fail.

Client error: `GET https://github.com/newroco/emlviewer/releases/download/1.0.5/emlviewer-1.0.5.tar.gz` resulted in a `404 Not Found` response: Not Found

**Comment by lucianpricop** [comment]
That's expected behavior because that release included a vendor folder compiled with php8 and for those with php7 NC crashed.
