### ISSUE TITLE
Compatibility to NC 26

### ISSUE THREAD

**Issue by DJeremyy** [newroco/emlviewer#56]
Hello and thank you very much for the work on this application which is very effective.

Do you think compatibility with Nextcloud 26 is envisaged?

**Comment by XueSheng-GIT** [comment]
I tired to enable emlviewer although not compatible with NC26, but it seems it doesn't work at all with NC26.

**Comment by 42ske** [comment]
in the meantime there is NC 27 published. Can you tell when emlviewer will be compatible?

**Comment by putt1ck** [comment]
Yes, it's alive but fixes are prioritised inline with client need, so compatibility work will be inline with their deployed version. PRs are of course welcomed!

**Comment by webermax** [comment]
> Yes, it's alive but fixes are prioritised inline with client need, so compatibility work will be inline with their deployed version. PRs are of course welcomed!

Thanks, I'm glad to hear it's continued.

What exactly is meant by "inline"?

**Comment by putt1ck** [comment]
Adding a space between "in" and "line" makes it clearer - basically when the client who wanted the app wants to upgrade their NC then EML Viewer will get some dev time (but PRs to achieve NC26+ compatibility welcomed).

**Comment by webermax** [comment]
All right, I see.

...and yes onboarding / PR is being considered.

**Comment by IgorA100** [comment]
I have emlviewer without global problems running on NC26.

**Comment by jpmv27** [comment]
NC25 is about to go EoL. Any chance of an update for compatibility with NC26 or later?

**Comment by IgorA100** [comment]
> NC25 is about to go EoL. Any chance of an update for compatibility with NC26 or later?

#58

**Comment by lucianpricop** [comment]
A new release for 25,26 and 27 is out.
