### ISSUE TITLE
NC28 Compatibility ? Call to undefined method OC\\Server::getEventDispatcher()

### ISSUE THREAD

**Issue by Mer0me** [newroco/emlviewer#59]
The app is not working on NC28. 

`{"reqId":"lUuc2c1DBVQDkCf0kqrq","level":4,"time":"2023-12-18T16:02:21+00:00","remoteAddr":"212.234.3.129","user":"--","app":"emlviewer","method":"POST","url":"/index.php/apps/text/session/203859/sync","message":"Error during app service registration: Call to undefined method OC\\Server::getEventDispatcher()","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0","version":"28.0.0.11","exception":{"Exception":"Error","Message":"Call to undefined method OC\\Server::getEventDispatcher()","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/emlviewer/lib/AppInfo/Application.php","line":68,"function":"registerScripts","class":"OCA\\EmlViewer\\AppInfo\\Application","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":142,"function":"register","class":"OCA\\EmlViewer\\AppInfo\\Application","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":90,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/nextcloud/lib/base.php","line":700,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/nextcloud/lib/base.php","line":1200,"function":"init","class":"OC","type":"::"},{"file":"/var/www/nextcloud/index.php","line":37,"args":["/var/www/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/emlviewer/lib/AppInfo/Application.php","Line":73,"message":"Error during app service registration: Call to undefined method OC\\Server::getEventDispatcher()","exception":{},"CustomMessage":"Error during app service registration: Call to undefined method OC\\Server::getEventDispatcher()"}}`

Some info here : https://help.nextcloud.com/t/symfony-event-dispatcher-update-in-nextcloud-server-28-breaking-changes/167550

**Comment by lucianpricop** [comment]
Thanks for letting us know. It's good we set it up as being supported on max v27.

**Comment by Mer0me** [comment]
Is there a plan to support NC 28 ?

**Comment by Mer0me** [comment]
Any news ? My company is using this app to archive mail. We cannot upgrade Nextcloud since this app is not compatible :(

**Comment by XueSheng-GIT** [comment]
> Any news ? My company is using this app to archive mail. We cannot upgrade Nextcloud since this app is not compatible :(

On my servers it also does not work on NC 27 anymore: https://github.com/newroco/emlviewer/issues/60

**Comment by lucianpricop** [comment]
We fixed the issues for NC27, but for NC28 the NC team changed the API a lot, it will require a lot more work and the documentation is scarce for app development. Will revisit in maybe 3 months.

**Comment by Mer0me** [comment]
Thank you for the update. I understand that it's not easy to maintain the app in these conditions...

**Comment by PeterLue** [comment]
The same error message was displayed in another project (OCCWEB). The solution here was the call
OC::$server->getEventDispatcher(),
through
OC::$server->get(\OCP\EventDispatcher\IEventDispatcher::class),
to replace. Just for info.

**Comment by Mer0me** [comment]
Just tried to replace the getEventDispacher function in the 2 files of emlviewer using it (lib/AppInfo/Application.php:73 and templates/index.php)
But it doesn't work better.

**Comment by lucianpricop** [comment]
Even if we fix that issue, when clicking on an eml file, NC will pass the click as a download request, emlviewer will not be used at all.

**Comment by lucianpricop** [comment]
Yes, we will create a version for NC28, but I can't commit to a certain deadline at this time.

**Comment by RaBla45** [comment]
Hallo,
gibt es neues zu diesem Punkt? Mein Nextcloud-Provider (Hetzner) nutzt bereits NC 28.0.6
Hello,
is there anything new on this point? My Nextcloud provider (Hetzner) is already using NC 28.0.6
Viele Grüße aus Berlin

**Comment by swordfish90s** [comment]
Hi,
Just adding to the chorus.  NC29.0.2 has the same error.  Currently disabled the emlviewer.
Thanks in advance for when you do get time to tackle this one.
Rob

**Comment by lucianpricop** [comment]
Thanks for letting us know. Will probably correct itself with a new release
