### ISSUE TITLE
NC 26.0.10 PHP Error ZBateson\StreamDecorators\SeekingLimitStream::seek

### ISSUE THREAD

**Issue by lancos** [newroco/emlviewer#60]
This is the log:
[PHP] Error: Declaration of ZBateson\StreamDecorators\SeekingLimitStream::seek($offset, $whence = ZBateson\StreamDecorators\SEEK_SET) must be compatible with Psr\Http\Message\StreamInterface::seek(int $offset, int $whence = Psr\Http\Message\SEEK_SET): void at /var/www/nextcloud/apps/emlviewer/vendor/zbateson/stream-decorators/src/SeekingLimitStream.php#126

**Comment by XueSheng-GIT** [comment]
Same error on NC 27.1.6 and Eml Viewer 1.0.8.
When trying to open an eml file, following error is shown:
```
Could not load data from server. undefined
```
Browser console shows:
```
500 Internal Server Error
```
