### ISSUE TITLE
Does not work with NC V 29.0x

### ISSUE THREAD

**Issue by tobefrank1** [newroco/emlviewer#63]
Used to be a very nice to have feature in NC, but obviously it only supports NC to V 27.

Anyway, thank you for the app.

**Comment by pat-githubber** [comment]
Agree, I miss this app :( thank you for your work 💙

**Comment by rubenixnagios** [comment]
we need to get this working again....can we help somehow?

TX and tx for ur great work!

**Comment by lucianpricop** [comment]
> we need to get this working again....can we help somehow?
> 
> TX and tx for ur great work!

Thanks. New NC is a different beast, we started to work on a version for NC29, but not been successful so far. Any code contribution is welcome.
