### ISSUE TITLE
Always"Preparing preview... please wait." but no preview

### ISSUE THREAD

**Issue by Michael2222** [newroco/emlviewer#8]
Hello,

I have installed the EML Viewer 0.0.5 on a nextcloud 17.0.3
After the click to an eml file, he write "Preparing preview... please wait." but he don't show mail preview.

Regards
   Michael

**Comment by RaBla45** [comment]
Hello,

I have the same problem.
I tried to use emlviewer 0.0.5 on nextcloud server from the provider hetzner. It seems to be nextcloud 17.0.2.
I used nextcloud in the webbrowser (firefox 73.0 - 64 Bit; Win10 Version 1903) .

Regards
Ralf

**Comment by Michael2222** [comment]
Hello @lucianpricop 
why do you close the issue and don't write the bug solution here?
Regards
  Michael

**Comment by DJCrashdummy** [comment]
@Michael2222 as mentioned in the close message, this should be fixed via https://github.com/newroco/emlviewer/commit/d183d2fb19a889e29a20636905a4e53ac027a710... if you don't upgrade to the latest master yourself, you may need some patience until a new release (with this fix) comes out.

**Comment by lucianpricop** [comment]
> Hello @lucianpricop
> why do you close the issue and don't write the bug solution here?
> Regards
> Michael

Hi Michael2222,
Sorry, there isn't much to explain, some paths were wrong in the code and I fixed them, the commit with my changes fixed the issue. We need some certificate updates before we can post a new release on NC official apps page, we're still waiting for their reply.

**Comment by Michael2222** [comment]
Hi,
thank you! Now it works fine!
